# Bienvenida {.unnumbered}

Este es el sitio web de la segunda edición de trabajo en progreso de **"R para la Ciencia de Datos"**.
Este libro le enseñará cómo hacer ciencia de datos con R: aprenderá cómo obtener sus datos en R, convertirlos en la estructura más útil, transformarlos y visualizarlos.

En este libro, encontrará ejercicios prácticos para aprender las habilidades necesarias para la ciencia de datos.
Así como un químico aprende a limpiar tubos de ensayo y abastecer un laboratorio, usted aprenderá a limpiar datos y dibujar diagramas, y mucho más.
Estas son las habilidades que hacen que exista la ciencia de datos, y aquí encontrará las mejores prácticas para hacer cada una de estas cosas con R.
Aprenderá a usar la gramática de los gráficos, la programación literaria y la investigación reproducible para ahorrar tiempo.
También aprenderá a administrar los recursos cognitivos para facilitar los descubrimientos al discutir, visualizar y explorar datos.

Este sitio web es y será siempre gratuito, bajo la licencia de [CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/us/) License.
Si desea una copia física del libro, puede pedir la primera edición en [Amazon](https://amzn.to/2aHLAQ1), o esperar hasta mediados de 2023 para la 2ª edición.
Si aprecia leer el libro gratis y desea retribuir, haga una donación a [Kākāpō Recovery](https://www.doc.govt.nz/kakapo-donate): el [kākāpō](https://www.youtube.com/watch?v=9T1vfsHYiKY) (que aparece en la portada de R4DS) es un loro nativo de Nueva Zelanda en peligro de extinsión; solo quedan 252.

Si habla otro idioma, es posible que le interesen las traducciones disponibles gratuitamente de la primera edición:

-   [Español](https://es.r4ds.hadley.nz)
-   [Italiano](https://it.r4ds.hadley.nz)
-   [Turco](https://tr.r4ds.hadley.nz)

Tenga en cuenta que R4DS utiliza un [Código de conducta del colaborador](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html).
Al contribuir a este libro, usted acepta cumplir con sus términos.

## Agradecimientos {.unnumbered}

R4DS está alojado por <https://www.netlify.com> como parte de su apoyo a las comunidades y el software de código abierto.
